---
- hosts: mixmaster
  tasks:
    - name: Install system packages
      become: yes
      dnf:
        name:
          - rakudo
          - rakudo-zef
        state: present
        update_cache: no
      tags:
        - firstrun

    - name: Install application packages
      become: yes
      command: "zef install {{ item }}"
      loop:
        - "JSON::Fast"
        - "Config::INI"
        - "Email::Simple"
        - "File::Temp"
      tags:
        - firstrun

    - name: Install application libraries
      become: yes
      copy:
        src: "{{ item }}"
        dest: "/usr/local/share/mixmaster/lib"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - "../lib/Broadcast"

    - name: Install application scripts
      become: yes
      copy:
        src: "{{ item }}"
        dest: "/usr/local/bin"
        owner: "root"
        group: "root"
        mode: "0755"
        setype: bin_t
      loop:
        - "../bin/mmbridge"
        - "../bin/mmbuild"
        - "../bin/mmcleanup"
        - "../bin/mmsetup"
